name: Scraper automático

on:
  schedule:
    - cron: '0 6 * * *'  # cada día a las 6am
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt supabase

      - name: Ejecutar scraper
        run: python supermarket-mercadona-scraper/scrape.py

      - name: Subir a Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python upload_to_supabase.py
