name: Scrape Mercadona y subir a Supabase

on:
  schedule:
    - cron: '0 6 * * *'  # Cada día a las 6am
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Mostrar estructura de carpetas
        run: |
          echo "Raíz del repo:"
          pwd
          echo "Contenido:"
          ls -la
          echo "Recursivo:"
          find .

      - name: Instalar dependencias
        run: |
          cd supermarket-mercadona-scraper
          pip install -r requirements.txt

      - name: Ejecutar scraper
        run: |
          cd supermarket-mercadona-scraper
          python scrape.py
