name: Scrape Mercadona y subir a Supabase

on:
  schedule:
    - cron: '0 6 * * *'  # Cada día a las 6am
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Mostrar estructura del proyecto
        run: |
          echo "Contenido raíz:"
          pwd
          ls -la
          find .

- name: Instalar dependencias
  run: |
    pip install -r supermarket-mercadona-scraper/requirements.txt

      - name: Ejecutar scraper
        run: |
          python scrape.py
