name: Diagnóstico estructura del repo

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mostrar estructura real del proyecto
        run: |
          echo "Directorio actual:"
          pwd
          echo "Contenido del directorio actual:"
          ls -la
          echo "Contenido completo del repositorio:"
          find .
      

