name: Scrape Mercadona y subir a Supabase

on:
  schedule:
    - cron: '0 6 * * *' # Cada día a las 6am
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Listar contenido raíz
        run: ls -la

      - name: Listar contenido carpeta supermarket-mercadona-scraper
        run: ls -la supermarket-mercadona-scraper || echo "No existe esa carpeta"

      - name: Ejecutar scraper
        run: |
          cd supermarket-mercadona-scraper
          python scrape.py
